# Generated by Django 5.0 on 2025-12-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.AlterField(
            model_name='productcolors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_colors/'),
        ),
    ]
