# Generated by Django 5.0 on 2025-12-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroapp', '0003_heroimage_youtubevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
