# Generated by Django 5.0 on 2025-12-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroapp', '0004_abouthero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
