# Generated by Django 5.0 on 2025-12-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroapp', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
