"""
Django settings for veroproject project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)y+e!df4yejzkym%w-9&_^-nt$b7q3fe)%q(_gx(=pg)ax0g9$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'veroapp',
    'rest_framework',
    'corsheaders',
    'nested_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'veroproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'veroproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py

JAZZMIN_SETTINGS = {
    # --------------------
    # Branding
    # --------------------
    "site_title": "VERO Admin",
    "site_header": "VERO",
    "site_brand": "VERO Footwear",
    "site_logo": "admin/images/vero-logo.jpg",
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": "admin/images/vero-logo.jpg",

    "welcome_sign": "Welcome to VERO Control Panel",
    "copyright": "VERO Footwear",

    # --------------------
    # Login Screen
    # --------------------
    "login_logo": "admin/logo-lg.svg",
    "login_logo_dark": "admin/logo-lg-dark.svg",
    "login_background": "admin/login-bg.jpg",

    # --------------------
    # Top Navigation
    # --------------------
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Website", "url": "/", "new_window": True},
        {"model": "auth.User"},
    ],

    # --------------------
    # Sidebar
    # --------------------
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["sessions"],
    "hide_models": ["auth.Group"],

    "order_with_respect_to": [
        "business",
        "products",
        "orders",
        "customers",
        "auth",
    ],

    # --------------------
    # Icons (FontAwesome)
    # --------------------
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "products.product": "fas fa-box",
        "products.productvariant": "fas fa-layer-group",
        "orders.order": "fas fa-shopping-bag",
        "orders.orderitem": "fas fa-receipt",
        "customers.customer": "fas fa-user-tie",
    },

    # --------------------
    # UI Tweaks
    # --------------------
    "related_modal_active": True,
    "custom_css": "admin/css/custom.css",
    "custom_js": "admin/js/custom.js",
    "show_ui_builder": False,
}


JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",

    "dark_mode_theme": "darkly",

    # Layout
    "sidebar_fixed": True,
    "navbar_fixed": True,
    "footer_fixed": False,

    # Visual polish
    "body_small_text": False,
    "brand_small_text": False,
    "sidebar_nav_small_text": False,

    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,

    # Buttons
    "button_classes": {
        "primary": "btn btn-primary",
        "secondary": "btn btn-outline-secondary",
        "success": "btn btn-success",
        "warning": "btn btn-warning",
        "danger": "btn btn-danger",
        "info": "btn btn-info",
    },
}
